// The model-neutral scenario that both sides of a cross-process comparison are
// driven from.
//
// Scope: a test contract, not a product API. It describes only the rigid-body
// constructs the current checks need — links, revolute joints, one free-floating
// body, a prescribed state and a prescribed excitation. There is no vehicle
// concept here and none is coming: a scenario that knew about wheelsets would
// shape the runtime interfaces around one consumer.
//
// The scenario declares the physical kind of each generalized-force component,
// while the judge owns the corresponding tolerance.
#pragma once

#include <string>
#include <vector>

#include <Eigen/Dense>

#include "contract/observation_semantics.h"

namespace orvd_contract {

struct LinkDefinition {
    std::string name;
    double mass_kilograms;
    Eigen::Vector3d center_of_mass_in_link_frame_meters;
    Eigen::Vector3d solid_box_full_extents_meters;
};

struct RevoluteJointDefinition {
    std::string name;
    std::string parent_link_name;  // empty means the world link
    std::string child_link_name;
    // Where the joint's parent frame sits on the parent link. The rotation is
    // part of it: a mount that is only ever displaced never exercises the code
    // that carries a rotation along the position chain, and the axis below is
    // stated in this frame, so a dropped rotation moves the axis too.
    Eigen::Matrix3d parent_frame_rotation_in_parent;
    Eigen::Vector3d parent_frame_translation_in_parent_meters;
    Eigen::Vector3d axis_in_parent;
};

struct RelativeSpatialVelocityObservationDefinition {
    std::string name;
    std::string moving_link_name;
    std::string reference_link_name;
    std::string expressed_in_link_name;
};

enum class GeneralizedForceComponentKind {
    kForceNewtons,
    kTorqueNewtonMetres,
};

struct ScenarioDefinition {
    double gravity_acceleration_meters_per_second_squared;
    std::vector<LinkDefinition> links;
    std::vector<RevoluteJointDefinition> revolute_joints;

    // Which links move freely in the world, stated rather than inferred from
    // "has no joint". One side of the comparison refuses to guess and the other
    // guesses silently; a scenario that left it unsaid would be describing two
    // different models to them.
    std::vector<std::string> free_body_names;

    // Prescribed state and excitation. Both sides are driven from these exact
    // numbers rather than from each implementation's own defaults.
    std::vector<double> generalized_positions;
    std::vector<double> generalized_velocities;
    std::vector<double> generalized_accelerations;
    std::vector<ObservationKind> generalized_position_observation_kinds;
    std::vector<ObservationKind> generalized_velocity_observation_kinds;
    std::vector<ObservationKind>
        generalized_position_derivative_observation_kinds;
    std::vector<GeneralizedForceComponentKind> generalized_force_component_kinds;

    // An independent velocity vector used by the forward map and to exercise
    // each public Jacobian as an operator. It differs from the state velocity,
    // and its entries are distinct, so neither a state read nor a column
    // permutation can substitute for the requested operation.
    std::vector<double> differential_kinematics_probe_generalized_velocities;

    // An independent qdot used by the inverse map. It is not generated by the
    // forward map and includes a quaternion-radial component, so the two maps
    // cannot validate one another by construction.
    std::vector<double>
        inverse_mapping_probe_generalized_position_derivatives;

    // Named independently of link-vector order. Both emitters resolve these
    // three links in the model they actually built.
    std::vector<RelativeSpatialVelocityObservationDefinition>
        relative_spatial_velocity_observations;

    // One generalized acceleration per mass-matrix column. Rotational entries
    // are rad/s² and translational entries are m/s². Every entry is non-zero so
    // every column produces an observable generalized-force response.
    std::vector<double> mass_matrix_column_generalized_accelerations;
};

// A two-link revolute chain, a revolute branch stated in the direction opposite
// the world-rooted forest, and one free-floating body. The joint axes are
// deliberately non-parallel: a chain whose joints share an axis cannot expose a
// sign or frame error in the off-diagonal inertia coupling.
//
// `excitation` selects the working point:
//   "near_zero_cancellation" — rest state; generalized forces collapse towards
//                              zero, which is where a spurious bias term shows.
//   "dynamic_excitation"     — non-zero velocities and accelerations chosen so
//                              the generalized forces are firmly away from zero.
[[nodiscard]] ScenarioDefinition MakeRevoluteChainWithFloatingBodyScenario(
    std::string_view excitation);

}  // namespace orvd_contract
